server:
  port: 9091
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/melissafilomeno/bug-tracker-poc-config
          search-paths:
            - tracker*
          repos:
            perf:
              pattern: '*/perf'
              uri: https://github.com/melissafilomeno/bug-tracker-poc-config-perf
              search-paths:
                - tracker*