server:
  port: 8888
encrypt:
  key: ${ENCRYPT_KEY}
spring:
  config:
    import: optional:file:.env[.properties]   # required to read properties from .env file
  security:
    user:
      name: ${CLOUD_CONFIG_USER}
      password: ${CLOUD_CONFIG_PASS}
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/${USER_HOME}/bug-tracker-poc-config
          search-paths:
            - tracker*
          repos:
            perf:
              pattern: '*/perf'
              uri: https://github.com/${USER_HOME}/bug-tracker-poc-config-perf
              search-paths:
                - tracker*